version: "3.3"
services:
  bot:
    build: .
    restart: always
    network_mode: "host"
    environment:
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      TELEGRAM_API_KEY: "${TELEGRAM_API_KEY}"
  redis:
    image: "redis"
    environment:
        REDIS_PASS_FILE: /run/secrets/redis-pass
    command: [
      "bash", "-c",
      '
       docker-entrypoint.sh
       --port 9876
      '
    ]
    restart: always
    network_mode: "host"
